/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fern_02_1k.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Fern(props) {
  const { nodes, materials } = useGLTF('/models/fern/fern_02_1k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.fern_02_b.geometry} material={materials.fern_02} />
      <mesh geometry={nodes.fern_02_c.geometry} material={materials.fern_02} position={[1, 0, 0]} />
      <mesh geometry={nodes.fern_02_a.geometry} material={materials.fern_02} position={[0, 0, 1]} />
      <mesh geometry={nodes.fern_02_d.geometry} material={materials.fern_02} position={[1, 0, 1]} />
    </group>
  )
}

useGLTF.preload('/models/fern/fern_02_1k.gltf')
