/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 shrub_01_1k.gltf 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Shrub(props) {
  const { nodes, materials } = useGLTF("/models/shrub/shrub_01_1k.gltf");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.shrub_01_a.geometry} material={materials.shrub_01} position={[0.6, 0, 0]} />
    </group>
  );
}

useGLTF.preload("/models/shrub/shrub_01_1k.gltf");
