/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 weed_plant_02_1k.gltf 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Weed(props) {
  const { nodes, materials } = useGLTF('/models/weed/weed_plant_02_1k.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.weed_plant_02_a_LOD0.geometry} material={materials.weed_plant_02} />
      <mesh geometry={nodes.weed_plant_02_b_LOD0.geometry} material={materials.weed_plant_02} position={[0.5, 0, 0]} />
      <mesh geometry={nodes.weed_plant_02_c_LOD0.geometry} material={materials.weed_plant_02} position={[1, 0, 0]} />
      <mesh geometry={nodes.weed_plant_02_d_LOD0.geometry} material={materials.weed_plant_02} position={[1.5, 0, 0]} />
      <mesh geometry={nodes.weed_plant_02_e_LOD0.geometry} material={materials.weed_plant_02} position={[2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/weed/weed_plant_02_1k.gltf')
